spring.application.name=clientProject
spring.datasource.url=jdbc:mariadb://localhost:3306/nhs_recruitment
spring.datasource.username=root
spring.datasource.password=comsc
spring.sql.init.mode=always
debug=false
server.port=8081

spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=nicholas99@ethereal.email
spring.mail.password=19YCXjVE8VpbeQuB5W
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.task.scheduling.enabled=true

logging.level.org.springframework.security=DEBUG

spring.messages.basename=messages
spring.thymeleaf.cache=false
server.error.include-stacktrace=never
